### PR TITLE
Add Sync Android app

### PR DESCRIPTION
**Pull request by danielpassos**
See: [RHMAP-2698](https://issues.jboss.org/browse/RHMAP-2698)

### CODE REVIEW

**Comment by danielpassos** [comment]
PS: I have no idea which version should I use in `package.json`

**Comment by danielpassos** [comment]
@jasonmadigan Could you give it a spin? I'm a little confused about the version

**Comment by jasonmadigan** [comment]
please retest this

**Comment by jasonmadigan** [comment]
@danielpassos i'll get this merged today.

**Comment by jasonmadigan** [comment]
Had to rebase - replaced with this PR: https://github.com/feedhenry/template-config/pull/79/

**Pull request closed without merging**
