### PR TITLE
FH-2293: Rename SAML template for Cordova

### PR DESCRIPTION
**Pull request by abstractj**
See: https://issues.jboss.org/browse/FH-2293

In order to merge this PR, before we have to rename https://github.com/feedhenry-templates/saml-client-app to saml-cordova-app. I didn't PR this, because i could't find a way to do this on GH without mess with the current structure.

I think we should tag all the templates and point global.json to the most stable version.

@jasonmadigan @wei-lee  mind to review?

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@abstractj reviewed - build failing because `saml-client-app` hasn't been renamed yet - can be rebuilt afterwards (to rebuild: just comment with "please retest this").

**Comment by abstractj** [comment]
please retest this

**Comment by abstractj** [comment]
@jasonmadigan not sure if these magical words worked, but the repo was renamed

**Comment by abstractj** [comment]
@jasonmadigan seems like didn't work or I don't have the powerz!

**Comment by abstractj** [comment]
@jasonmadigan are we good to merge this change?

**Comment by jasonmadigan** [comment]
@abstractj ping me when you're about - you're in the owners team so should be able to merge (may need to rebase)

**Comment by jasonmadigan** [comment]
Am okay with this master merge (even with the `master` freeze), since it just changes a repo URL (which is redirecting anyway).

**Pull request merged**
