### PR TITLE
Adding SAML Service

### PR DESCRIPTION
**Pull request by jasonmadigan**

### CODE REVIEW

**Comment by cianclarke** [comment]
Aw, wish our builds didn't fail pre-merge on the images https://raw.githubusercontent.com/feedhenry-templates/saml-service/master/files/icon.png

**Comment by jasonmadigan** [comment]
@cianclarke d'oh! I'll rebuild, pushed that image.

**Comment by cianclarke** [comment]
Looks good

**Comment by jasonmadigan** [comment]
Merging, I'll put together an fhcap PR

**Pull request merged**
