### PR TITLE
Add SAML apps - "Don't not merge yet"

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@edewit @corinnekrych @jasonmadigan Could you please review it?

**Comment by jasonmadigan** [comment]
@danielpassos this looks fine. Could we hold off on merging this to master until we rebuild templates for 3.5.3? (We really need a better branching/tagging strategy for our templates!)

**Comment by danielpassos** [comment]
@jasonmadigan Off course. I'll update the PR with "Don't not merge yet"

**Comment by danielpassos** [comment]
Closing for now. I'll open another one to `FH-v3.7.0`

**Pull request closed without merging**
