### PR TITLE
Switch hello world to fh42 branch

### PR DESCRIPTION
**Pull request by nialldonnellyfh**
Not for merging yet.

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@nialldonnellyfh assume this isn't going to be merged until 3.5.0?

**Comment by nialldonnellyfh** [comment]
@jasonmadigan Exactly, only here so I can generate template apps for delta. Will be merged back for the 3.5.0 release.

**Comment by jasonmadigan** [comment]
Perfect

**Comment by nialldonnellyfh** [comment]
retest this please

**Comment by fh-team-eng** [comment]
Build finished. Test FAILed.

**Comment by nialldonnellyfh** [comment]
retest this please

**Comment by nialldonnellyfh** [comment]
retest this please

**Comment by nialldonnellyfh** [comment]
retest this please

**Pull request merged**
